package com.example.mydatabase.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.mydatabase.greendao.Photo;
import com.example.mydatabase.greendao.User;

import com.example.mydatabase.greendao.PhotoDao;
import com.example.mydatabase.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig photoDaoConfig;
    private final DaoConfig userDaoConfig;

    private final PhotoDao photoDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        photoDaoConfig = daoConfigMap.get(PhotoDao.class).clone();
        photoDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        photoDao = new PhotoDao(photoDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Photo.class, photoDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        photoDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public PhotoDao getPhotoDao() {
        return photoDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
